# Generated by Django 5.1.1 on 2024-10-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='activate',
            new_name='active',
        ),
    ]
